---
title: "Stat 31631"
author: "B.T.M.Ekanayaka"
date: "2024-08-04"
output: word_document
---

```{r}
# Install and load necessary libraries
#install.packages("tidyverse")
library(tidyverse)

# Load the data set
# Assuming the data set is in a CSV file named "mobile_phone_price_prediction.csv"
data <- read.csv("C:\\Users\\LENOVO\\Downloads\\Mobile.csv")

# View the first few rows of the dataset
head(data)

#Descriptive Analysis
summary(data)

```
```{r}
library(ggplot2)


# 1. Linear Regression
linear_model <- lm(Price ~ Selfi_Cam, data=data)
summary(linear_model)

#Scatter_Plot
plot(data$Selfi_Cam, data$Price, main="Linear Regression: Price vs Selfi_Cam",xlab="Selfi_Cam", ylab="Price", col="blue")
abline(linear_model, col="red")

# 2. Non-Linear Regression
poly_model <- lm(Price ~ poly(Selfi_Cam, 2), data=data)
summary(poly_model)
plot(data$Selfi_Cam, data$Price, main="Non Linear Regression: Price vs Selfi_Cam",
     xlab="Selfi_Cam", ylab="Price", pch=19, col="blue")
Selfi_Cam_seq <- seq(min(data$Selfi_Cam), max(data$Selfi_Cam), length.out=100)
predicted_price <- predict(poly_model, newdata=data.frame(Selfi_Cam=Selfi_Cam_seq))
lines(Selfi_Cam_seq, predicted_price, col="red")

# 3. Multiple Linear Regression
multiple_linear_model <- lm(Price ~ Selfi_Cam + RAM + ROM + Mobile_Size + Primary_Cam + Ratings + Battery_Power, data=data)
summary(multiple_linear_model)
par(mfrow=c(2, 2))
plot(multiple_linear_model)



```
